using ReportPdfFileWriter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PdfFileWriter;
using System.Diagnostics;
using System.Drawing;
using TestPdfFileWriter;

namespace ReportPdfFileWriter.Controllers
{
    public class HomeController : Controller
    {
        WeeklyReport weeklyreport = new WeeklyReport();
        ////
        // GET: /Home/

        public ActionResult Index()
        {
            //ViewData["Message"] = "Press Button to download report (pdf)";
            //return View();
            ArticleExample AE = new ArticleExample();
            AE.Test(false, "D:\\Rsc\\ReportPdfFileWriter\\ReportPdfFileWriter\\ReportPdfFileWriter\\ReportPdfFileWriterWeeklyReportpdf.pdf");
            return View();
        }

        public ActionResult GenPDF()
        {
            //ArticleExample AE = new ArticleExample();
            //AE.Test(false, "D:\\Rsc\\ReportPdfFileWriter\\ReportPdfFileWriter\\ReportPdfFileWriter\\WeeklyReportpdf.pdf");
            return null;
            //return File(filename, "WeeklyReportpdf");
        }

        public void WeeklyreportTempList()
        {
            MonthData Temp = new MonthData();
            Temp.Month = "NOVEMBER 2013";
            Temp.Revenue = 789000;
            Temp.Forecast = 789000;
            weeklyreport.Months.Add(Temp);

            MonthData Temp2 = new MonthData();
            Temp2.Month = "DECEMBER 2013";
            Temp2.Revenue = 79000;
            Temp2.Forecast = 99000;
            weeklyreport.Months.Add(Temp2);

            MonthData Temp3 = new MonthData();
            Temp3.Month = "JANUARY 2014";
            Temp3.Revenue = 89000;
            Temp3.Forecast = 59000;
            weeklyreport.Months.Add(Temp3);

            MonthData Temp4 = new MonthData();
            Temp4.Month = "FEBRUARY 2014";
            Temp4.Revenue = 79000;
            Temp4.Forecast = 69000;
            weeklyreport.Months.Add(Temp4);

            MonthData Temp5 = new MonthData();
            Temp5.Month = "MARCH 2014";
            Temp5.Revenue = 78000;
            Temp5.Forecast = 29000;
            weeklyreport.Months.Add(Temp5);

            weeklyreport.Logo = "http://www.primesrms.com/assets/new_logo-a309b42703b3f2b5f7a93e15d35898d5.png";
            weeklyreport.ReportName = "WEEKLY REPORT";
            weeklyreport.LabelMonth = "MONTH";
            weeklyreport.LabelRevenue = "REVENUE";
            weeklyreport.LabelForecast = "FORECAST";
            weeklyreport.LabelFooter = "Generated by PRIMES©";
            weeklyreport.GeneratedOn = DateTime.UtcNow;

        }
    }
}
